version: '3.8'

services:
  client:
    image: node:22.2.0
    volumes:
      - ./steganography-client:/app
    working_dir: /app
    environment:
      - VITE_SSL_ENABLED=${SSL_ENABLED}
      - VITE_API_DOMAIN=${API_DOMAIN}
    command: >
      bash -c "
        npm install && npm run debug
      "
    ports:
      - "${CLIENT_SERVER_PORT}:4321"

  api:
    image: python:3.12
    volumes:
      - ./steganography-api:/app:z
      - ./files:/app/files:z
    working_dir: /app
    environment:
      - IS_DEBUG=true
    command: >
      bash -c "
        pip install -r requirements.txt && python app.py
      "
    ports:
      - "${API_SERVER_PORT}:8080"